-
  branches:
    except:
      - stable
  skip_branch_with_pr: true
  version: '{branch}-build{build}'
  skip_tags: true
  clone_depth: 1
  configuration:
    - Debug
    - Release
  before_build:
    - ps: Import-Module .\build\psake.psm1
    - ps: $env:VERSION_SUFFIX = 'preview' + "$env:APPVEYOR_BUILD_NUMBER".PadLeft(4, "0")
  build_script:
    - ps: |
        Invoke-Psake .\build\build.ps1 -properties @{"Configuration"=$env:CONFIGURATION;"VersionSuffix"=$env:VERSION_SUFFIX}
        if ($psake.build_success -eq $false) { exit 1 }
  test: off
  artifacts:
    - path: 'artifacts\*.nupkg'
  deploy:
    on:
      configuration: Debug
    provider: NuGet
    api_key:
      secure: T+mZG82JKtFeFvMcDiQPrDCTxoFIjmnWAg6bufXFChOmq9smm6BMQSQVBXGNqZkH
    artifact: /.*\.nupkg/
-
  branches:
    only:
      - stable
  version: '{branch}-build{build}'
  skip_tags: true
  clone_depth: 1
  configuration: Release
  before_build:
    - ps: Import-Module .\build\psake.psm1
  build_script:
    - ps: |
        Invoke-Psake .\build\build.ps1 -properties @{"Configuration"=$env:CONFIGURATION}
        if ($psake.build_success -eq $false) { exit 1 }
  test: off
  artifacts:
    - path: 'artifacts\*.nupkg'
  deploy:
    provider: NuGet
    api_key:
      secure: T+mZG82JKtFeFvMcDiQPrDCTxoFIjmnWAg6bufXFChOmq9smm6BMQSQVBXGNqZkH
    artifact: /.*\.nupkg/